CREATE TABLE IF NOT EXISTS Facts (
  ID SERIAL PRIMARY KEY,
  Fact VARCHAR
);

CREATE TABLE IF NOT EXISTS Cats (
  ID SERIAL PRIMARY KEY,
  Name VARCHAR,
  LifeSpan VARCHAR,
  Colors VARCHAR,
  Description VARCHAR
);
